### ISSUE TITLE
Missing groupbox labels on the options window

### ISSUE THREAD

**Issue by MaxKoll** [revad/use_bcc_instead_C#1]
### Bug description:
The groupbox headings as specified in `chrome/content/AddonOptions.xul` don't show on the options panel. This happens on Linux and it is currently unknown if it also happens on other platforms.

### Actual result:
![screenshot_use_bcc_instead_c_options_1](https://user-images.githubusercontent.com/3061165/51045620-fa110d80-15bb-11e9-90bc-5a5bc1ce9ec3.png)

### Expected result:
This screenshot shows the options panel in Thunderbird 60.4.0 and it's the way it should look:

![options panel with groupbox headings](https://user-images.githubusercontent.com/39014485/51062266-a53eb880-15f6-11e9-9b12-95f6d98b0d2e.png)

### Steps to reproduce:
Open the options panel.

**Comment by revad** [comment]
I see the same issue - no groupbox labels - in another addon I'm trying to convert. I suspect this is a fault in the legacy overlay loader.

**Comment by revad** [comment]
Various XUL elements have been removed by the XUL/XBL replacement proect. For example listbox was removed as mentioned in [XUL/XBL Replacement Newsletter 7](https://briangrinstead.com/blog/xbl-replacement-newsletter-7). This is reflected in the [TB 63 addon migration notes](https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_63#Removed_in_Thunderbird_63)

[Newsletter 9](https://briangrinstead.com/blog/xbl-replacement-newsletter-9)  mentions some changes to groupbox and refers to [bug 1493844](https://bugzilla.mozilla.org/show_bug.cgi?id=1493844) which refers to preferences.

That bug doesn't suggest to me that groupbox is being removed, but I think that bug is implicated in this issue.

**Comment by revad** [comment]
I asked in bugzilla and got confirmation that this is indeed caused by the change made under bug  1493844.

https://bugzilla.mozilla.org/show_bug.cgi?id=1476259#c17
